/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samuel
 */
public class Hauptfenster extends javax.swing.JFrame {

    /**
     * Creates new form Hauptfenster
     */
    public Hauptfenster(Controller c, View v) {
        controller = c;
        view = v;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        bNameText = new javax.swing.JLabel();
        bVornameText = new javax.swing.JLabel();
        bKontonummerText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        kontostandButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        auszahlungText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        auszahlenButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        zielNummerText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ueberweisungBetragText = new javax.swing.JTextField();
        ueberweisenButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        abmeldenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ihr Bankkonto");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        bNameText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bNameText.setText("Name:");

        bVornameText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bVornameText.setText("Vorname:");

        bKontonummerText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bKontonummerText.setText("Kontonummer:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bKontonummerText)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bNameText)
                        .addComponent(bVornameText)))
                .addContainerGap(597, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bNameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bVornameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bKontonummerText)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Benutzer", jPanel1);

        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        kontostandButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kontostandButton.setText("Kontostand abfragen");
        kontostandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontostandButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(kontostandButton)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(kontostandButton)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kontostand", jPanel2);

        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Betrag der Auszahlung:");

        auszahlungText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        auszahlungText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Euro");

        auszahlenButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        auszahlenButton.setText("Auszahlen");
        auszahlenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auszahlenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(auszahlenButton)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(auszahlungText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auszahlungText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(auszahlenButton)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Auszahlung", jPanel3);

        jPanel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Zielkontonummer:");

        zielNummerText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Betrag der Überweisung:");

        ueberweisungBetragText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ueberweisungBetragText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ueberweisenButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ueberweisenButton.setText("Überweisen");
        ueberweisenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ueberweisenButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Euro");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ueberweisenButton)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zielNummerText)
                        .addComponent(ueberweisungBetragText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zielNummerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ueberweisungBetragText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(ueberweisenButton)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Überweisung", jPanel4);

        jPanel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        abmeldenButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        abmeldenButton.setText("Abmelden");
        abmeldenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmeldenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(abmeldenButton)
                .addContainerGap(617, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(abmeldenButton)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Abmelden", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void auszahlenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auszahlenButtonActionPerformed
        view.auszahlenButton();
    }//GEN-LAST:event_auszahlenButtonActionPerformed

    private void kontostandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontostandButtonActionPerformed
        view.kontostandButton();
    }//GEN-LAST:event_kontostandButtonActionPerformed

    private void ueberweisenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ueberweisenButtonActionPerformed
        view.ueberweisenButton();
    }//GEN-LAST:event_ueberweisenButtonActionPerformed

    private void abmeldenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmeldenButtonActionPerformed
        view.abmeldenButton();
    }//GEN-LAST:event_abmeldenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void guiStarten() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Hauptfenster hauptFenster = new Hauptfenster(controller, view);
                hauptFenster.setVisible(true);
                view.setHauptFenster(hauptFenster);
                view.benutzerPanel();
            }
        });
    }
    
    //Get Methoden
    public javax.swing.JTextField getAuszahlungText() {
        return auszahlungText;
    }
    
    public javax.swing.JTextField getUeberweisungBetragText() {
        return ueberweisungBetragText;
    }
    
    public javax.swing.JTextField getZielNummerText() {
        return zielNummerText;
    }
    
    public javax.swing.JLabel getBNameText() {
        return bNameText;
    }
    
    public javax.swing.JLabel getBVornameText() {
        return bVornameText;
    }
    
    public javax.swing.JLabel getBKontonummerText() {
        return bKontonummerText;
    }
    //Get Methoden End

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abmeldenButton;
    private javax.swing.JButton auszahlenButton;
    private javax.swing.JTextField auszahlungText;
    private javax.swing.JLabel bKontonummerText;
    private javax.swing.JLabel bNameText;
    private javax.swing.JLabel bVornameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kontostandButton;
    private javax.swing.JButton ueberweisenButton;
    private javax.swing.JTextField ueberweisungBetragText;
    private javax.swing.JTextField zielNummerText;
    // End of variables declaration//GEN-END:variables
    private Controller controller;
    private View view;
}

